feat: flag to manage sequenced rollout #201
apigee/apigeecli pull request #202
Opened 2023-05-09 22:46 UTC by srinandan

2023-05-10 03:00 UTC, ssvaidyanathan approved these changes

2023-05-10 04:41 UTC, ssvaidyanathan commented
Still unclear how this field will fix the issue? I called the Mgmt API with that property set to `true` and was able to deploy the same revision to two environments part of the same env group. So how will the routing happen? Will this field make sure that the call goes to the latest deployed environment?

2023-05-10 14:21 UTC, kurtkanaskie commented
There's an error on the query param for the flag:
has: q.Set("sequencedRollout", serviceAccountName)
should be: q.Set("sequencedRollout", sequencedRollout)

2023-05-10 14:54 UTC, kurtkanaskie commented
Just testing this out now, the use of sequencedRollout true or false does not prevent the deployment to another env in the same envGroup.

The use of generateDeployChangeReport will indicate: "New deployment will not receive any traffic for basepath /notarget, as this basepath is already claimed by proxy notarget in environment test."

It's up to the user in the UI or the tool invoking the APIs to choose to continue with deployment or not. Even in the UI I can ignore the generateDeployChangeReport and deploy to another env in the same envGroup.

2023-05-10 15:58 UTC, ssvaidyanathan commented on cmd/apis/depapi.go
> +		false, "If set to true, generateDeployChangeReport will executed and deployment will proceed if there are no conflicts; default is false")
will `be` executed

2023-05-10 16:49 UTC, ssvaidyanathan commented
> Why is `generateDeployChangeReport` default false? Shouldn't it be true to prevent unexpected behavior, like having a proxy deployed to 2 envs in the same envGroup?

Probably for backward compatibility?

2023-05-10 17:04 UTC, kurtkanaskie commented
> Probably for backward compatibility?

I think that behavior is a bug.

2023-05-10 20:18 UTC, ssvaidyanathan approved these changes

2023-05-10 20:58 UTC, kurtkanaskie requested changes
One minor editorial on L56

undeployment will proceed...

2023-05-10 20:58 UTC, kurtkanaskie commented on cmd/apis/undepapi.go
> +			"deployment will proceed if there are no conflicts; default is true")
undeployment will proceed

2023-05-10 21:29 UTC, kurtkanaskie approved these changes

2023-05-10 21:34 UTC, merged

2023-05-11 14:16 UTC, Pavloro commented
It works as expected now. Thank you for your quick response and fix!