fixed path issue in import kvm, #303 #304
apigee/apigeecli pull request #305
Opened 2023-09-27 07:25 UTC by aliasgar55

Fixed issue with import kvm

2023-09-29 16:19 UTC, kurtkanaskie commented on cmd/kvm/impkvms.go
> +                kvmFile := filepath.Base(orgKVMFile)
Change whitespace to match the file: space --> tab

2023-09-29 16:19 UTC, kurtkanaskie commented on cmd/kvm/impkvms.go
> +                kvmFile := filepath.Base(envKVMFile)
Change whitespace to match the file: space --> tab

2023-09-29 16:20 UTC, kurtkanaskie commented on cmd/kvm/impkvms.go
> +                kvmFile := filepath.Base(proxyKVMFile)
Change whitespace to match the file: space --> tab

2023-09-29 16:21 UTC, kurtkanaskie requested changes
Given the folders and kvm files:
```
kvm-import-tests/
├── kvms-env
│   └── env_bu1-test_bu1-kvm2_kvmfile_0.json
├── kvms-org
│   └── org_test-org-level2_kvmfile_0.json
└── kvms-proxy
    └── proxy_bu1-test-1_bu1-test-1-kvm_kvmfile_0.json
```
ORG=apigeex-payg-kurt
ENV=bu1-test
PROXY=bu1-test-1

The file names structure being: 
env_${ENV}_${KVM}_kvmfile_0.json
proxy_${$PROXY}_${KVM}_kvmfile_0.json
org_${KVM}_kvmfile_0.json

I verified that the following has an error:
```
apigeecli kvms import --folder=./kvm-import-tests/kvms-proxy --org=$ORG
```

And that this works:
```
go run main.go -t=$TOKEN kvms import --folder=./kvm-import-tests/kvms-proxy --org=$ORG
```

All other imports work too.

Change whitespace to match the file: space --> tab.

2023-09-30 05:53 UTC, aliasgar55 commented
Fixed the spacing issue

2023-10-02 13:38 UTC, kurtkanaskie approved these changes
Thanks, LGTM

2023-10-02 15:09 UTC, ssvaidyanathan commented
@aliasgar55 - we will be able to merge once you accept the CLA
You need to go to https://cla.developers.google.com/ and accept.

2023-10-03 16:32 UTC, kurtkanaskie commented
> Please run `gofumpt -w .` from the root folder. I think that's the last remaining issue.

It took me a bit to get this installed. 
First I had to upgrade go to 1.19 or greater, I used 1.21.1
Then I installed with `go install mvdan.cc/gofumpt@latest` which put gofump in $HOME/go/bin
Then I added that to my path.

When I ran, it flagged an empty line #42 and removed it.

2023-10-05 19:52 UTC, merged