bug: fixes missing expiry during update #341
apigee/apigeecli pull request #343
Opened 2023-12-02 19:16 UTC by srinandan

2023-12-02 19:17 UTC, srinandan commented
This doesn't fix the issue. But I think it is necessary.

2023-12-04 21:35 UTC, kurtkanaskie requested changes
App keys APIs are kinda confusing and messy.
I can generate new keys, assign to product and set expiration using a single API call: https://cloud.google.com/apigee/docs/reference/apis/apigee/rest/v1/organizations.developers.apps/generateKeyPairOrUpdateDeveloperAppStatus

Or I can import external keys (but not expiration) using: https://cloud.google.com/apigee/docs/reference/apis/apigee/rest/v1/organizations.developers.apps.keys/create
And then add product using: https://cloud.google.com/apigee/docs/reference/apis/apigee/rest/v1/organizations.developers.apps.keys/updateDeveloperAppKey

So how do I generate app keys via apigeecli?
This requires key and secret
apps keys create --org=$ORG --dev=demo@any.com --name=demo-app --expires=2678389502 --prods=demo

2023-12-05 18:57 UTC, srinandan commented
To generate a new key pair:

```
apigeecli apps genkey --help
Generate a new developer KeyPair

Usage:
  apigeecli apps genkey [flags]

Flags:
  -c, --callback string      The callbackUrl is used by OAuth
  -d, --devid string         Developer Id
  -x, --expires string       A setting, in milliseconds, for the lifetime of the consumer key
  -h, --help                 help for genkey
  -n, --name string          Name of the developer app
  -p, --prods stringArray    A list of api products
  -s, --scopes stringArray   OAuth scopes
```

2023-12-13 22:37 UTC, kurtkanaskie commented
The expires flag is now in seconds consistently and only used for `apps keys create` and `apps genkey`.
Removed required secret from `apps keys udpate`, its not needed.

2023-12-13 22:42 UTC, srinandan commented on cmd/apps/updatekey.go
> +		_, err = apps.UpdateKey(developerEmail, name, key, secret, apiProducts, scopes, attrs)
Since secret is not passed, why keep it as a parameter?

2023-12-13 22:43 UTC, srinandan commented on internal/client/apps/keys.go
> +		apiclient.ClientPrintHttpResponse.Set(true)
Instead of true, please replace with `apiclient.ClientPrintHttpResponse.Set(apiclient.GetCmdPrintHttpResponseSetting())`

2023-12-14 18:17 UTC, kurtkanaskie approved these changes

2023-12-14 19:48 UTC, merged